language: ruby
rvm:
- 2.3.1
env:
  test:
    APIKEY: stub-key
    MAP_APIKEY: stub-key
    WEATHER_APIKEY: stub-key
  global:
  - secure: vpYfB530r8dB+CYjP0Mz0KoZvAtDsu55KoE2Q4WS4Z21NZA0tAWDLZglQqqLVgS7l9XzyOoQeYciCL90+iN9RWPXAk7jsUo5RWo63V2BmqgyMIFlObpg/KGzEufT9a2Tyjn7cb5eBBpF2KlNFHh05GG9U746iDQ0iB0kxdBfkuH4LoFf9RaBrh6SIgmuJdrnbOiyFv2Ye3VpzdcjDYLQY8Ry4uPHEUNNUi7OufovawKZnmqi11BWluFJ7TDcqdy6E1LswfZmz/y9qnomztQC1JDEBBT9EiJ8V09hLZY9QmmD3zn5j14c5MlcT4gizTIV/YpS52rdfMf9mJH0WzRZC3PRQe4K8mOhE8/2yuUWHiYZsJioLCvlhuEjeYYsfV9dzPADcSm1JgfDwAqdA7nwB663gcDb5SsI1gEqEHkv6rZfXEsozPdzPBoHXrgvSvmZfMnzxmeVlGXHF8ihyfyq2JtF7VqVGa62DMeAZvsFGhtGw4V52S0AnD9GdwMH+FeKDfIhSKFjd1oTS66vSZ+GZT0Frh7lrHLAgBZmeQD9iChFNklszfeme1E0BWCb8Gia7Ki0DmAw/vFOfZ6+Ad2s/0wKgJIRH6suNX48YBESEQpAgc4ltIOIny7bmEo8dwGaQ/w3ru/G+ofnpCMmGHgtx1J5S8NMpVl0xqJaiMRFOXo=
  - secure: n8ADwLPEgNrHC2EkAynvuvJiqQsR0yyNp3wSA5DvGifAo0CfVUDW6d/nduub1x6Z2GWuUCW/v0AKfdKekcLykksJgSx3KoqxlCU+DwGfVSYeFQFOY+LANDjbSQI+nsjG1/r/GVZFFVoftGNSW+5tdyUsvyese1CEuh/hO3v8PLl542WvPD4PPFSrvt6XXgKBLrr4EWYivHwnNRyQjQNAL4qLXbEmvLzz8S9B4f+U61a8UswLEaXzPTMeHkpgizkXjeZabQFXe5dAPWd1H25P0S8f86FWFu1J+TzgK8UsooO8IfXXjbtD+kb3IMKXToRaLaYrjvMLx8jy2e7uZOKdHTTVjSwGDtyk9we41jXq5RZsYWylFx9mrxjpE46+4mfnvAGoYZFlBzph9BtiMfd8pBeyAq5uOfy30TyddHrwEUcU+RcTqsmS5s0b9PPkH1759gh0XhXmRd53iOWzQyOzJSvT39ziachlLrUbq5ib+0Dao3DihxD8zasZbNxFXB5MlZuZ+yJ5AVujFzyeu3tFaTPCTlbQieMIvzoF5W1Ij43y8VaMfhkRNFLzMQk7FDTH8+4n2BHVXvgvHPoXVDm82+oTEwrTiT/2iQZB+zp4qWhw9Cv3k7AnFAHy/aoaaqgZSWAlNBcxY0FRv/oWG050hotpkp0MRQZDCoqLt5EKS4Y=
  - secure: TGSKdmvP3jwuiCYOgkF+q8XrsUDD03JHrXggn0hTeYbMioX9pLe4YzAeVopMuIGWahUM0nlr+hDrHAGZYK4+P80h+jqcsB6pXWF1HNo7CROF269M34hzj6+okZkvC1Yj0WsiH8Qh+P8WXRq6qtwz1bE49wnoWfRo/EWQ1jaXb8mS2J4Jh8cwtF30k75SZN0a+Xyn2PRdPPQIxtmKOyxe59p7O7sAuQNX0MtLVR2vJx6apUt6m0WJ1Y14NQwQdPqai1eRfrtTK18BtFIYjh3T8yJmxlX8cGRu8jkSmji/2yI7C1gySuUEFF0M7pPdvUB0SY/KzFeGllBe0lbYmHKbBb4AVWQPCPIUbfR+GkLZEMAhS0qkKqlheq3W1WTMOVlnqClMSzdDA3sOczSGCtt2V6M/oqVZOEfRo3DfoB5mHIIRJve74i+0QoACz3ftOeSZnDf2N04uTK4+rawJCKd0kNNEQOJd+fveEyhwauPWe7xYRVzdPBs2nBkkDx+iZWHA8vO6YbxoyeJbloHmlSFUDDVqJub6r7PBnXSUUehwgfkMKId4xpcKuFq6eknQPwsr9QLIc5zHbTFg4cHSq2K2KaAzTk/9S4/tnrhF/aM2v471gcDlRN9sWYZeWqTeYjuhHtq5vKhIoeruekl4ktGeli9OCl66eGDqnYV0W6qrqYo=
addons:
  sauce_connect:
    username: odporkka
  jwt:
    secure: AlNqGbGGRU1qN7tlFsE/kUmeYBmmlIByf9N9W4bLqtbYAMBLZCkj/3CgOKDdlim7UHlcay4Y0gi4oHARcd3sxbK2AiN8ClocC0GCOQBhSPv4z3v+CP7PfUW8jTavbF93twDcIr4JHrabVuPK/T0L3rn7lJ/B3nVl8QsE2a8i3/u4pau/uu4X41bHNnf66Tx3XGrZd9rFuQM7cIzV0ObD+eL/bXcblRWWrALOgtqu1Y0ffUNmiCg3W4J6qZiULcSpJTp0W9yQE1K7V7XmcY2wtYH4Ej1W2H856yr6RqkypzGDDy/7U7hWL6QARyvonKmsM2soHHHJnbglERkJAfZ1T+miiQ7a1Ue2/VE3WcgUx955hHsWkTjde2xn47ZycJArfqBUEDwLwgzkywGtkQ7VhFRUATgn9d4T8JavHXhI2KWFSUC0kLxjq/gvDnKkJ0ndor3ptUAe7dx8hHA/ufRgVQvA+qJh80mWmYBxBCNINP8+1G3uNee+Lo9rhq2sIwL804CziMfacXe27cj+zBUAGsadx0S9Nxy2hnfNJNyWZY6GFcFTjnRbA1yCXKN81ei+69i5MUPNUokzfYQFjt4saOnsH+Kjd1B67CZSzXYXCRfPK+CQfwzGZVce/YI0rk00nHhRxqlxprtTC6y+4t/aPmBVViABFTC4TfzmE6RnMII=
before_install:
- sudo apt-get -qq update 
- sudo apt-get install -y xvfb firefox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- rackup
- sleep 3
script:
- bundle exec rake db:drop db:create db:migrate db:seed --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
notifications:
  email: false
deploy:
  provider: heroku
  app: rubyonrails2017
  api_key:
    secure: bdUoS7O85bZzI4JXjOjkBEZEX/0I9NfikpJOdBBLvgPIOdwcoSLbAYOGoMHS9k0VfGOFVVqOfIfJUrFtg3rVOkNPh7DAwB+wTVGtADLUokcHrvFT5ttodaX8TNfwtz5L3hZlqBePcT+swJ68nFtQ3PTNnNofaJ0q0K48T96ec0N62XL+rDPrXZHoqwr9qjh4eP6mgNkDCKb753BUlTW3rIkv8CO963HeLhFTaPO3vrHwhYOm6oKfF7zQAfTcKBufitV7rwE21EbS5JMx1kvYpWNQ8x1G5jGTvMpofA+XMO9sOwWvQ3QA+G5YlbELXMZxqhVnd/d3odHQEcprznA+sQy7t/ljyBS8o1ZQ4SEAccONHmQm7iSjHZRpedBrPPjAfNVEi5yx3wwQgJubFEcg76rnsCEkRsdSODm6/y1Zxxyhod2YkqAcHJ0grys9yEi2Q5Z1Mtv9waxrQ2jnbr+Cwq5KosOPZcubQihp7wYng4qEp+uDANJ/ys6sTRRA5ZU9uqkG5ygpW0VF1x8jbDxkFSJNXsQErP/h/cCSQZRXnzf9TaaxcBSXwNr8BscRkRWOkSWsJKole3G44+HhcNLEfhK0D0xGzmTbSIMhJPMdUXniuBBScngcUAKu8jm779zoa/BzE8gVNv5mIRNQqyEzb4hmhghR1HE7RVO6v2FEI1k=
  run: rake db:migrate
