defaults: &defaults
  APIKEY: #key for beermapping-api
  MAP_APIKEY: #key for google maps
  WEATHER_APIKEY: #key for weather
development:
        <<: *defaults
test:
        <<: *defaults
production:
        <<: *defaults
